### PR TITLE
Faculty Fragment Added

### PR DESCRIPTION
**Pull request by lakshyagupta21**
Details of CSE Faculty fragment Added

### CODE REVIEW

**Comment by vjs3** [comment]
@lakshyagupta21 why are you working on master branch itself?

**Comment by lakshyagupta21** [comment]
@vjs3  Forgot that .

**Comment by vjs3** [comment]
There are lot of conflicts already.

**Comment by lakshyagupta21** [comment]
Please discard this PR, I will close this PR, create a fresh branch and then send the PR again. Sorry for any inconvenience.

**Comment by vjs3** [comment]
Yes sure! go ahead!

Vishwajeet Srivastava
_Google Summer of Code'16 Intern @Mifos_
Contact Number: +91-9783553169
Blog: vishwajeetsrivastava.com

**Pull request closed without merging**
